type Profile {
  userName: String!
  coins: Int!
  stash: [Item!]
  ships: [Ship!]
}

type Item {
  id: String!
  quantity: Int!
}

type Ship {
  id: String!
  shipId: String!
}

type Query {
  healthCheck: Boolean
  profile: Profile
  userExists(userName: String!): Boolean
  totalPlayers: Int
}

type Mutation {
  createProfile(userName: String!): Profile
  updateProfile(userName: String!): Profile
  deleteProfile: Boolean
  sellItem(itemId: String!, quantity: Int!): Profile
  buyItem(itemId: String!, quantity: Int!): Profile
}
